// Popular dog breeds list for auto-suggestions
export const DOG_BREEDS = [
  'Golden Retriever',
  'Labrador Retriever',
  'German Shepherd',
  'French Bulldog',
  'Bulldog',
  'Poodle',
  'Beagle',
  'Rottweiler',
  'German Shorthaired Pointer',
  'Dachshund',
  'Yorkshire Terrier',
  'Boxer',
  'Siberian Husky',
  'Great Dane',
  'Doberman Pinscher',
  'Shih Tzu',
  'Boston Terrier',
  'Pomeranian',
  'Havanese',
  'Shetland Sheepdog',
  'Brittany',
  'Pembroke Welsh Corgi',
  'Australian Shepherd',
  'Cavalier King Charles Spaniel',
  'Miniature Schnauzer',
  'Cocker Spaniel',
  'Border Collie',
  'Chihuahua',
  'Maltese',
  'Pug',
  'Shiba Inu',
  'Akita',
  'Chow Chow',
  'Samoyed',
  'Basset Hound',
  'Saint Bernard',
  'Newfoundland',
  'Bernese Mountain Dog',
  'Vizsla',
  'Weimaraner',
  'Rhodesian Ridgeback',
  'Dalmatian',
  'Mastiff',
  'Bichon Frise',
  'Bull Terrier',
  'Bloodhound',
  'Cane Corso',
  'Alaskan Malamute',
  'Papillon',
  'Whippet',
  'English Springer Spaniel',
  'Belgian Malinois',
  'Collie',
  'Staffordshire Bull Terrier',
  'Scottish Terrier',
  'West Highland White Terrier',
  'Cairn Terrier',
  'American Pit Bull Terrier',
  'Mixed Breed',
  'Other'
];

// Popular temperament tags
export const TEMPERAMENT_TAGS = [
  'Friendly',
  'Playful',
  'Energetic',
  'Calm',
  'Loyal',
  'Affectionate',
  'Intelligent',
  'Protective',
  'Independent',
  'Social',
  'Gentle',
  'Curious',
  'Active',
  'Lazy',
  'Shy',
  'Bold',
  'Trainable',
  'Stubborn',
];
